### ISSUE TITLE
Fetch data from remote source

### ISSUE THREAD

**Issue by calmwalija** [calmwalija/Training#18]
### Tasks

- [ ] Add the dependencies for making HTTP requests
- [ ] Get data from this [url](https://jsonplaceholder.typicode.com/posts/1/comments)
- [ ] Create an `entity `and a `model `for the `comments`
- [ ] Use single source of truth to view this data
